#pragma config(Motor,  port1,           CMot,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port2,           RRevs,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LFors,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port4,           RLift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LLift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RFors,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LRevs,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          CLift,          tmotorVex393_MC29, openLoop)



//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
void rightMotors(int num)
{
	motor[RRevs] = -num;
	motor[RFors] = num; //wires have reverse polarity
}
void leftMotors(int num)
{
	motor[LRevs] = -num;
	motor[LFors] = num; //wires have reverse polarity
}
void BotLift()
{
	 	while(vexRT[Btn6U])
	 	{
    	motor[RLift] = 120;
  		motor[LLift] = 120;
    }
	  while(vexRT[Btn6D])
	 	{
	   	motor[RLift] = -120;
   		motor[LLift] = -120;
    }
	  motor[RLift] = 0;
	  motor[LLift] = 0;
}

void Claw()
{
	if(vexRT(Btn7D))
	{
		motor[CMot] = 127;
  }
  else if(vexRT(Btn7U))
  {
    motor[CMot] = -127;
  }
  else
  {
  	motor[CMot] = 0;
  }

}

/*void ClawLIft()
{
	if (vexRT[Btn5U])
  {
		ClawUp();
	}
  else if(vexRT[Btn5D])
  {
		ClawDown();
	}
	else
  {
  }
}*/

task usercontrol()
{
  // User control code here, inside the loop


  while (true)
  {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.

    int deadZone = 15;

		if (vexRT[Ch2] > deadZone || vexRT[Ch2] < -deadZone)
		{
			rightMotors(vexRT[Ch2]);

		} else {
			rightMotors(0);
		}

		if (vexRT[Ch3] > deadZone || vexRT[Ch3] < -deadZone)
		{
			leftMotors(vexRT[Ch3]);
		} else {

			leftMotors(0);
		}
		//ClawLift();
		Claw();
		BotLift();




    // ........................................................................

    // Remove this function call once you have "real" code.
  }
}
