#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in8,    Potent,         sensorPotentiometer)
#pragma config(Sensor, dgtl5,  LimL1,          sensorTouch)
#pragma config(Sensor, dgtl6,  LimR1,          sensorTouch)
#pragma config(Sensor, dgtl11, stackEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9, REnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl7, LEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           CMot,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LMots1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LMots2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMots3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           MobMots1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RMots1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RMots2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RMots3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           MobMots2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftMot,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "DriveControls.h"
int TargetHeight = 0;
int minS = 20;

void resetEnc()
{
	SensorValue[stackEnc] = 0;
}

void MoveArm( int deg)
{
	time1[T1] = 0;
	while (time1[T1] < 10000){
TargetHeight = deg;
motor[LiftMot] = -(TargetHeight - SensorValue[stackEnc])*3;
//The constant should be a float value set to around 0.08
}
}

void MoveArmAt(int deg, int time)
{
		TargetHeight = deg;
		int speed = -(TargetHeight - SensorValue[stackEnc])*4;
		if (abs(speed) < minS)
		{
			if (speed < 0)
			{
			motor[LiftMot] = -minS;
			}
			else
			{
			motor[LiftMot] = minS;
			}
		}
		else
			{
    		motor[LiftMot] = speed;
  		}
    		wait10Msec(time);
    motor[LiftMot] = 0;
//The constant should be a float value set to around 0.08
}

task main()
{
	//setupController();
	resetEnc();

		MoveArm(-100);
		wait10Msec(700);
		//MoveArmAt(80, 700);
		//wait10Msec(700);
		//MoveArmAt(0, 700);
		//wait10Msec(700);

	//runController();


}
