#pragma config(Sensor, dgtl11, stackEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           CMot,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LMots1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LMots2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LMots3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           MobMots1,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           RMots1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RMots2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RMots3,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           MobMots2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftMot,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
#pragma config(Sensor, dgtl11, stackEnc,       sensorQuadEncoder)
#pragma config(Motor,  port1,           CMot,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port2,           RMots1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RMots2,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RMots3,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           MobMots1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LMots1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LMots2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LMots3,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           MobMots2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LiftMots,      tmotorVex393_MC29, openLoop)*/
//*!!Code automatically generated by 'ROBOTC' configuration wizard     !!*//
//Ports 2-4 right drive motors (port 2 is y cabled)
//Ports 6-8 left drive motors (Ports 6 is y cabled)
//Ports 5 & 9 e chain bar lift
//code is changeare goal lift motors
//Port 1 are claw motor
//Port 10 is thd after new rewiring
//power expander on ports 4 & 5 & 8 & 9
int n = 1;
#include "DriveControls.h"

task main() //Boff
{
setupController();
  while (true)
  {
  	if (vexRT[Btn7U] == 1)
		{
			n = n * -1;
		}
  runController();
	  if (vexRT[Btn8R] == 1)
		{
			motor[LiftMot] = -127;
		}
		else if (vexRT[Btn8D] == 1)
		{
			motor[LiftMot] = 127;
		}
		else
		{
			motor[LiftMot] = 0;
		}
		if (vexRT[Btn5U] == 1)
		{
			motor[MobMots1] = -127;
			motor[MobMots2] = -127;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[MobMots1] = 127;
			motor[MobMots2] = 127;
		}
		else
		{
			motor[MobMots1] = 0;
			motor[MobMots2] = 0;
		}
  }
}
