//#pragma config(Sensor, in1,    Gyro,           sensorGyro)
//#pragma config(Sensor, in8,    Potent,         sensorPotentiometer)
//#pragma config(Sensor, dgtl1,   LED1,           sensorLEDtoVCC)
//#pragma config(Sensor, dgtl2,   LED1,           sensorLEDtoVCC)
//#pragma config(Sensor, dgtl3,   LED1,           sensorLEDtoVCC)
//#pragma config(Sensor, dgtl4,   LED1,           sensorLEDtoVCC)
//#pragma config(Sensor, dgtl5,  LimL1,          sensorTouch)
//#pragma config(Sensor, dgtl6,  LimR1,          sensorTouch)
//#pragma config(Sensor, dgtl7,  LEnc,           sensorQuadEncoder)
//#pragma config(Sensor, dgtl9,  REnc,           sensorQuadEncoder)
//#pragma config(Sensor, dgtl11, stackEnc,       sensorQuadEncoder)
//#pragma config(Motor,  port1,           CMot,          tmotorVex393_HBridge, openLoop, reversed)
//#pragma config(Motor,  port2,           LMots1,        tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port3,           LMots2,        tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port4,           LMots3,        tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port5,           MobMots1,      tmotorVex393_MC29, openLoop, reversed)
//#pragma config(Motor,  port6,           RMots1,        tmotorVex393_MC29, openLoop, reversed)
//#pragma config(Motor,  port7,           RMots2,        tmotorVex393_MC29, openLoop, reversed)
//#pragma config(Motor,  port8,           RMots3,        tmotorVex393_MC29, openLoop, reversed)
//#pragma config(Motor,  port9,           MobMots2,      tmotorVex393_MC29, openLoop)
//#pragma config(Motor,  port10,          LiftMot,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//This is actually the drive


//3s are middles
#include "v2DriveControls.h"
void resetEnc()
{
	SensorValue[stackEnc] = 0;
}

task runControl()
{
	while (true)
	{
		runPID();
		wait1Msec(10); // avoids cpu hog
  }
}
/*task clawCont()
{
	while (true)
	{
	  clawPow();
	  wait1Msec(10);
  }
}*/
task runLift ()
{
  while(true)
  {
    lift();
    //liftCheck();
  }
}
void drive()
{
	setVariables();
	setupController();
	//resetEnc();
	SensorValue[stackEnc] = 0;
	//startTask(clawCont);
	startTask(runControl);
	startTask(runLift);
  while(true)
  {
		runController();
		//if (vexRT[controller.stack] == 1)
		//{
			//rotatate for  degrees using P control
		wait1Msec(10); // avoids cpu hog
  }
}


//task main()
//{
//	SetupSens();
//	setupController();
//	resetEnc();
//	//startTask(clawCont);
//	startTask(runControl);
//	startTask(runLift);
//  while(true)
//  {
//		runController();
//		//if (vexRT[controller.stack] == 1)
//		//{
//			//rotatate for  degrees using P control
//		wait1Msec(10); // avoids cpu hog
//  }
//}
