#pragma config(Motor,  port2,           one,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           two,           tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		if(vexRT[Btn8R] == 1){
			motor[one] = 127;
		}else{
			motor[one] = 0;
		}

		if(vexRT[Btn7L] == 1){
			motor[two] = 127;
		}else{
			motor[two] = 0;
		}
	}


}
